server:
  port: 8002
  servlet:
    context-path: /sso2
security:
  oauth2:
    client:
      client-id: client2
      client-secret: secret
      user-authorization-uri: http://127.0.0.1:8000/oauth/authorize
      access-token-uri: http://127.0.0.1:8000/oauth/token
    resource:
      token-info-uri: http://127.0.0.1:8000/oauth/check_token