server:
  port: 9001
  servlet:
    context-path: /sso1
security:
  oauth2:
    client:
      client-id: client1
      client-secret: secret
      user-authorization-uri: http://127.0.0.1:8002/oauth/authorize
      access-token-uri: http://127.0.0.1:8002/oauth/token
    resource:
      token-info-uri: http://127.0.0.1:8002/oauth/check_token